# Test Environment Overrides
# Isolated test environment for integration tests
# Uses different ports and databases to avoid conflicts with development

services:
  # Test infrastructure with isolated ports
  qdrant:
    ports:
      - "6337:6333"  # gRPC - avoid conflict with dev
      - "6338:6334"  # HTTP - avoid conflict with dev
    volumes:
      - ./data/test_qdrant_data:/qdrant/storage

  mongo:
    ports:
      - "27018:27017"  # Avoid conflict with dev
    volumes:
      - ./data/test_mongo_data:/data/db
    command: mongod --dbpath /data/db --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok", "--quiet"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    ports:
      - "6380:6379"  # Avoid conflict with dev
    volumes:
      - ./data/test_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Test backend with test-specific configuration
  friend-backend:
    ports:
      - "8001:8000"  # Avoid conflict with dev
    volumes:
      - ./src:/app/src
      - ./data/test_audio_chunks:/app/audio_chunks
      - ./data/test_debug_dir:/app/debug_dir
      - ./data/test_data:/app/data
    environment:
      # Test database connections
      - MONGODB_URI=mongodb://mongo:27017/test_db
      - QDRANT_BASE_URL=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379/0
      - DEBUG_DIR=/app/debug_dir
      # Test authentication
      - AUTH_SECRET_KEY=test-jwt-signing-key-for-integration-tests
      - ADMIN_PASSWORD=test-admin-password-123
      - ADMIN_EMAIL=test-admin@example.com
      # Test provider configuration
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-deepgram}
      - MEMORY_PROVIDER=${MEMORY_PROVIDER:-friend_lite}
      - MYCELIA_URL=http://mycelia-backend:5173
      - MYCELIA_DB=mycelia_test
      # Test-specific settings
      - DISABLE_SPEAKER_RECOGNITION=false
      - SPEAKER_SERVICE_URL=https://localhost:8085
      - CORS_ORIGINS=http://localhost:3001,http://localhost:8001
      - SPEECH_INACTIVITY_THRESHOLD_SECONDS=2  # Fast timeout for tests
      - WAIT_FOR_AUDIO_QUEUE_DRAIN=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/readiness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Test workers
  workers:
    volumes:
      - ./src:/app/src
      - ./data/test_audio_chunks:/app/audio_chunks
      - ./data/test_debug_dir:/app/debug_dir
      - ./data/test_data:/app/data
    environment:
      # Same environment as test backend
      - MONGODB_URI=mongodb://mongo:27017/test_db
      - QDRANT_BASE_URL=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379/0
      - DEBUG_DIR=/app/debug_dir
      - AUTH_SECRET_KEY=test-jwt-signing-key-for-integration-tests
      - ADMIN_PASSWORD=test-admin-password-123
      - ADMIN_EMAIL=test-admin@example.com
      - TRANSCRIPTION_PROVIDER=${TRANSCRIPTION_PROVIDER:-deepgram}
      - MEMORY_PROVIDER=${MEMORY_PROVIDER:-friend_lite}
      - MYCELIA_URL=http://mycelia-backend:5173
      - MYCELIA_DB=mycelia_test
      - DISABLE_SPEAKER_RECOGNITION=false
      - SPEAKER_SERVICE_URL=https://localhost:8085
      - SPEECH_INACTIVITY_THRESHOLD_SECONDS=2
      - WAIT_FOR_AUDIO_QUEUE_DRAIN=true

  # Test webui
  webui:
    build:
      args:
        - VITE_BACKEND_URL=http://localhost:8001
        - BACKEND_URL=http://localhost:8001
    ports:
      - "3001:80"  # Avoid conflict with dev
    volumes:
      - ./webui/src:/app/src

  # Test Mycelia backend
  mycelia-backend:
    ports:
      - "5100:5173"  # Test backend port
    environment:
      # Test JWT secret
      - JWT_SECRET=test-jwt-signing-key-for-integration-tests
      - SECRET_KEY=test-jwt-signing-key-for-integration-tests
      # Test database
      - MONGO_URL=mongodb://mongo:27017
      - MONGO_DB=mycelia_test
      - DATABASE_NAME=mycelia_test
      # Test Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:5173/health').then(r => r.ok ? Deno.exit(0) : Deno.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Test Mycelia frontend
  mycelia-frontend:
    build:
      args:
        - VITE_API_URL=http://localhost:5100
    ports:
      - "3002:8080"
    environment:
      - VITE_API_URL=http://localhost:5100
