# Infrastructure Services
# Core database and cache services required by all environments

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_GRPC_PORT:-6033}:6333"
      - "${QDRANT_HTTP_PORT:-6034}:6334"
    volumes:
      - ${QDRANT_DATA_PATH:-../data/qdrant_data}:/qdrant/storage
    networks:
      - infra-network
      - chronicle-network

  mongo:
    image: mongo:8.0.14
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - infra-network
      - chronicle-network

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ${REDIS_DATA_PATH:-../data/redis_data}:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - infra-network
      - chronicle-network

networks:
  infra-network:
    driver: bridge
  chronicle-network:
    name: chronicle-network
    external: true

volumes:
  mongo_data:
    driver: local
