# Observability Stack
# Langfuse for LLM tracing and monitoring
# Enable with: docker compose --profile observability up

services:
  langfuse-server:
    image: langfuse/langfuse:latest
    ports:
      - "${LANGFUSE_PORT:-3000}:3000"
    environment:
      - DATABASE_URL=${LANGFUSE_DATABASE_URL:-postgresql://postgres:postgres@langfuse-db:5432/langfuse}
      - NEXTAUTH_SECRET=${LANGFUSE_NEXTAUTH_SECRET:-changeme}
      - NEXTAUTH_URL=${LANGFUSE_URL:-http://localhost:3000}
      - SALT=${LANGFUSE_SALT:-changeme}
    depends_on:
      langfuse-db:
        condition: service_healthy
    profiles:
      - observability
    restart: unless-stopped
    networks:
      - chronicle-network

  langfuse-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=langfuse
    volumes:
      - langfuse_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - observability
    restart: unless-stopped
    networks:
      - chronicle-network

networks:
  chronicle-network:
    name: chronicle-network
    external: true

volumes:
  langfuse_db:
    driver: local
