#!/bin/bash
# Generate Caddyfile with subdomain routing for active environments
# This script scans environments/ directory and creates routes for each

set -e

CADDY_DIR="caddy"
CADDYFILE="${CADDY_DIR}/Caddyfile"

# Create caddy directory if it doesn't exist
mkdir -p "${CADDY_DIR}"

# Get Tailscale hostname from config
if [ -f "config-docker.env" ]; then
    source config-docker.env
fi

if [ -z "$TAILSCALE_HOSTNAME" ]; then
    echo "❌ TAILSCALE_HOSTNAME not configured"
    echo "   Run: make setup-tailscale"
    exit 1
fi

echo "📝 Generating Caddyfile for Tailscale hostname: ${TAILSCALE_HOSTNAME}"
echo ""

# Start Caddyfile
cat > "${CADDYFILE}" << EOF
# Auto-generated Caddyfile for Friend-Lite multi-environment routing
# Generated by scripts/generate-caddyfile.sh
# Uses path-based routing: https://hostname/env/...

# Global options
{
    # Use Tailscale HTTPS certificates
    auto_https off
}

https://${TAILSCALE_HOSTNAME} {
    tls /certs/${TAILSCALE_HOSTNAME}.crt /certs/${TAILSCALE_HOSTNAME}.key

EOF

# Scan environments directory
if [ ! -d "environments" ]; then
    echo "⚠️  No environments directory found"
    exit 1
fi

env_count=0
for env_file in environments/*.env; do
    [ -f "$env_file" ] || continue

    # Extract environment name
    env_name=$(basename "$env_file" .env)

    # Load environment to get port offset and compose project name
    source "$env_file"

    # Calculate ports
    WEBUI_PORT=$((3010 + PORT_OFFSET))
    BACKEND_PORT=$((8000 + PORT_OFFSET))

    # Use COMPOSE_PROJECT_NAME from environment file (or fall back to friend-lite-${env_name})
    if [ -z "$COMPOSE_PROJECT_NAME" ]; then
        COMPOSE_PROJECT_NAME="friend-lite-${env_name}"
    fi

    # Container names with compose project prefix
    WEBUI_CONTAINER="${COMPOSE_PROJECT_NAME}-webui-1"
    BACKEND_CONTAINER="${COMPOSE_PROJECT_NAME}-friend-backend-1"

    echo "   Adding route: /${env_name}/*"
    echo "      WebUI:   ${WEBUI_CONTAINER}"
    echo "      Backend: ${BACKEND_CONTAINER}"

    # Add path-based route for this environment
    cat >> "${CADDYFILE}" << EOF
    # ${env_name} environment
    # Redirect exact path without trailing slash
    @${env_name}_exact path /${env_name}
    redir @${env_name}_exact /${env_name}/

    # Mycelia routes (if Mycelia is enabled)
    handle_path /${env_name}/mycelia/* {
        # Mycelia backend API routes
        @mycelia_api path /api/* /oauth/*
        handle @mycelia_api {
            reverse_proxy ${COMPOSE_PROJECT_NAME}-mycelia-backend-1:5100
        }

        # Mycelia frontend - serve all other paths
        handle {
            reverse_proxy ${COMPOSE_PROJECT_NAME}-mycelia-frontend-1:8080 {
                header_up X-Forwarded-Prefix /${env_name}/mycelia
            }
        }
    }

    # handle_path automatically strips prefix for paths with trailing slash
    handle_path /${env_name}/* {
            # Backend routes
            @api path /api/*
            @auth path /auth/*
            @users path /users/*
            @ws path /ws* /ws_pcm*
            @health path /health /readiness
            @docs path /docs* /openapi.json

            handle @api {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }
            handle @auth {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }
            handle @users {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }
            handle @ws {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }
            handle @health {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }
            handle @docs {
                reverse_proxy ${BACKEND_CONTAINER}:8000
            }

        # WebUI - serve all other paths
        handle {
            reverse_proxy ${WEBUI_CONTAINER}:80 {
                header_up X-Forwarded-Prefix /${env_name}
            }
        }
    }

EOF

    env_count=$((env_count + 1))
done

# Close the server block
cat >> "${CADDYFILE}" << 'EOF'
    # Root path - show environment list
    handle / {
        respond `
<html>
<head><title>Friend-Lite Environments</title></head>
<body>
<h1>Friend-Lite Environments</h1>
<p>Select an environment:</p>
<ul>
EOF

# Add links to each environment
for env_file in environments/*.env; do
    [ -f "$env_file" ] || continue
    env_name=$(basename "$env_file" .env)
    echo "<li><a href=\"/${env_name}/\">${env_name}</a></li>" >> "${CADDYFILE}"
done

cat >> "${CADDYFILE}" << 'EOF'
</ul>
</body>
</html>
` 200
    }
}
EOF

echo ""
echo "✅ Caddyfile generated: ${CADDYFILE}"
echo "📊 Configured ${env_count} environment(s):"
echo ""
for env_file in environments/*.env; do
    [ -f "$env_file" ] || continue
    env_name=$(basename "$env_file" .env)
    echo "   • ${env_name}"
done
echo ""
echo "💡 After starting an environment, it will be accessible at:"
echo "   https://${TAILSCALE_HOSTNAME}/<env-name>/"
echo ""
